Bot started at: 2024-01-08 11:19:33.517394
Traceback (most recent call last):
  File "bot.py", line 63, in <module>
  File "selenium\webdriver\chrome\webdriver.py", line 45, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 61, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 209, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 293, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 348, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 229, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
	GetHandleVerifier [0x00516EE3+174339]
	(No symbol) [0x00440A51]
	(No symbol) [0x00156FF6]
	(No symbol) [0x0017A756]
	(No symbol) [0x00177A0F]
	(No symbol) [0x001AE259]
	(No symbol) [0x001ADBBA]
	(No symbol) [0x001A6DA6]
	(No symbol) [0x00181034]
	(No symbol) [0x00181F8D]
	GetHandleVerifier [0x005B4B1C+820540]
	sqlite3_dbdata_init [0x006753EE+653550]
	sqlite3_dbdata_init [0x00674E09+652041]
	sqlite3_dbdata_init [0x006697CC+605388]
	sqlite3_dbdata_init [0x00675D9B+656027]
	(No symbol) [0x0044FE6C]
	(No symbol) [0x004483B8]
	(No symbol) [0x004484DD]
	(No symbol) [0x00435818]
	BaseThreadInitThunk [0x75CFFCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77AF7C6E+286]
	RtlGetAppContainerNamedObjectPath [0x77AF7C3E+238]
	(No symbol) [0x00000000]

